import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1777610009982 implements MigrationInterface {
    name = 'Migration1777610009982'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP CONSTRAINT "FK_user_firebase_tokens_user"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_created_by_user"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_deleted_by_user"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_updated_by_user"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_notifications_user"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "FK_currency_organization"`);
        await queryRunner.query(`ALTER TABLE "country" DROP CONSTRAINT "FK_country_organization"`);
        await queryRunner.query(`ALTER TABLE "buyer" DROP CONSTRAINT "FK_buyer_organization"`);
        await queryRunner.query(`ALTER TABLE "embellishment" DROP CONSTRAINT "FK_embellishment_organization"`);
        await queryRunner.query(`ALTER TABLE "color" DROP CONSTRAINT "FK_color_organization"`);
        await queryRunner.query(`ALTER TABLE "size" DROP CONSTRAINT "FK_size_organization"`);
        await queryRunner.query(`ALTER TABLE "styles" DROP CONSTRAINT "FK_styles_organization"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "FK_uom_organization"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_organization_access_requests_created_by_user"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_organization_access_requests_deleted_by_user"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_organization_access_requests_requested_admin_user"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_organization_access_requests_requested_by_user"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_organization_access_requests_requested_organization"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_organization_access_requests_reviewed_by_user"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_organization_access_requests_updated_by_user"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_menu_module"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_menu_to_org_map_menu"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_menu_to_org_map_organization"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_menu_permission_menu"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_menu_permission_organization"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_menu_permission_user"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_user_to_oranization_map_default_per_user"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_currency_organization"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_country_organization"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_buyer_organization"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_embellishment_organization"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_color_organization"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_size_organization"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_styles_organization"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_uom_organization"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_organization_access_requests_pending_unique"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_organization_access_requests_status_created"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_module_entry_active"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_menu_module_id"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_menu_to_org_map_organization"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_menu_to_org_map_menu"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_menu_permission_user"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_menu_permission_menu"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_menu_permission_organization"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP COLUMN "requested_organization_id"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD "updated_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD "deleted_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "buyer" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "buyer" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_organization_access_requests_pending_admin_unique"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ALTER COLUMN "requested_admin_user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ALTER COLUMN "requested_admin_email" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD "updated_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD "deleted_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "updated_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "deleted_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menu" ALTER COLUMN "module_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD "updated_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD "deleted_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD "created_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD "updated_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD "deleted_by_id" uuid`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_organization_access_requests_pending_admin_unique" ON "organization_access_requests" ("requested_by_user_id", "requested_admin_user_id") WHERE "status" = 'pending'`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD CONSTRAINT "FK_459c426aa96644dec9c5f4592f4" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD CONSTRAINT "FK_279b368eefe5181cd0dc3ae77b9" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD CONSTRAINT "FK_3ee453584a07b441959281b3b74" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD CONSTRAINT "FK_2383d7b0b279626153d2f65deb9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_8abe9303bccd29799a4d435eb03" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_4b5a99e362f41866311bc381b2d" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_104254bdc074b18a64110127250" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "FK_bd21ca257afac5b2f44fc951073" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country" ADD CONSTRAINT "FK_e5d33a5b71443865b5c6a1eea22" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyer" ADD CONSTRAINT "FK_403e838f0f6cf324609bb8575ff" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embellishment" ADD CONSTRAINT "FK_dc7b2b6cccbb57a0790619c73bc" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "color" ADD CONSTRAINT "FK_aac149527499d062a6f1a16224a" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "size" ADD CONSTRAINT "FK_e07817a7f74ccc73a911612622d" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "styles" ADD CONSTRAINT "FK_fe3905f0b4179308667f52a46b2" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "FK_843aee500ddeae1f82e32290d67" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_ff216adf95db9488195158439e3" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_7f679ddf7aba1f4aaa6a1a8ad3f" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_69496f6123908e6fa1402cba94a" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_a1b7a1009abf045715d50f92a4e" FOREIGN KEY ("requested_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_82c97ce5284af4ce0b98de79b2a" FOREIGN KEY ("requested_admin_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_b5a849368b063f5738ee5a3c8e0" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD CONSTRAINT "FK_d85fae0200638edf5716e924d6d" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD CONSTRAINT "FK_0634d875dd0aef4069eff1d7422" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD CONSTRAINT "FK_7eecd8afdf4f706ccc31e5186b9" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_3897d3db594dbeb79b057026bfb" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_7d328b7644258940a6f5190e745" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_a13e8815bbd246baedd2bb13eec" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_d68a151a9ee82114c44aa7dee5f" FOREIGN KEY ("module_id") REFERENCES "module_entry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_183277307f37ad2d617af8c2ab2" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_52b53b913acc50551f861cc4c13" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_b4177ebd06c162d958074e4a8b9" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_2e5a31dce6a84351342bc318614" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_e1ae7e97a01b0745e200258eff0" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_7801af81a04b6ffeec445f15d27" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_780dd539248c486ef69c48172e5" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_14fc1f4e99ce05b30fd19c636a1" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_f5041fba59a63e32cbd0bcb900d" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_8ab337e75d1f19a11a6b3dc2de4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_b3c8638bfd2ffedfc593ba3d034" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_b3c8638bfd2ffedfc593ba3d034"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_8ab337e75d1f19a11a6b3dc2de4"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_f5041fba59a63e32cbd0bcb900d"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_14fc1f4e99ce05b30fd19c636a1"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_780dd539248c486ef69c48172e5"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_7801af81a04b6ffeec445f15d27"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_e1ae7e97a01b0745e200258eff0"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_2e5a31dce6a84351342bc318614"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_b4177ebd06c162d958074e4a8b9"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_52b53b913acc50551f861cc4c13"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_183277307f37ad2d617af8c2ab2"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_d68a151a9ee82114c44aa7dee5f"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_a13e8815bbd246baedd2bb13eec"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_7d328b7644258940a6f5190e745"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_3897d3db594dbeb79b057026bfb"`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP CONSTRAINT "FK_7eecd8afdf4f706ccc31e5186b9"`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP CONSTRAINT "FK_0634d875dd0aef4069eff1d7422"`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP CONSTRAINT "FK_d85fae0200638edf5716e924d6d"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_b5a849368b063f5738ee5a3c8e0"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_82c97ce5284af4ce0b98de79b2a"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_a1b7a1009abf045715d50f92a4e"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_69496f6123908e6fa1402cba94a"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_7f679ddf7aba1f4aaa6a1a8ad3f"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_ff216adf95db9488195158439e3"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "FK_843aee500ddeae1f82e32290d67"`);
        await queryRunner.query(`ALTER TABLE "styles" DROP CONSTRAINT "FK_fe3905f0b4179308667f52a46b2"`);
        await queryRunner.query(`ALTER TABLE "size" DROP CONSTRAINT "FK_e07817a7f74ccc73a911612622d"`);
        await queryRunner.query(`ALTER TABLE "color" DROP CONSTRAINT "FK_aac149527499d062a6f1a16224a"`);
        await queryRunner.query(`ALTER TABLE "embellishment" DROP CONSTRAINT "FK_dc7b2b6cccbb57a0790619c73bc"`);
        await queryRunner.query(`ALTER TABLE "buyer" DROP CONSTRAINT "FK_403e838f0f6cf324609bb8575ff"`);
        await queryRunner.query(`ALTER TABLE "country" DROP CONSTRAINT "FK_e5d33a5b71443865b5c6a1eea22"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "FK_bd21ca257afac5b2f44fc951073"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_104254bdc074b18a64110127250"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_4b5a99e362f41866311bc381b2d"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_8abe9303bccd29799a4d435eb03"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP CONSTRAINT "FK_2383d7b0b279626153d2f65deb9"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP CONSTRAINT "FK_3ee453584a07b441959281b3b74"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP CONSTRAINT "FK_279b368eefe5181cd0dc3ae77b9"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP CONSTRAINT "FK_459c426aa96644dec9c5f4592f4"`);
        await queryRunner.query(`DROP INDEX "code_crafter_x"."IDX_organization_access_requests_pending_admin_unique"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD "deleted_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD "updated_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD "created_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD "deleted_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD "updated_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD "created_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "menu" ALTER COLUMN "module_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "deleted_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "updated_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "menu" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "menu" ADD "created_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD "deleted_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD "updated_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD "created_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ALTER COLUMN "requested_admin_email" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ALTER COLUMN "requested_admin_user_id" DROP NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_organization_access_requests_pending_admin_unique" ON "organization_access_requests" ("requested_admin_user_id", "requested_by_user_id") WHERE ((status = 'pending'::organization_access_requests_status_enum) AND (requested_admin_user_id IS NOT NULL))`);
        await queryRunner.query(`ALTER TABLE "buyer" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "buyer" ADD "is_active" character varying(10) NOT NULL DEFAULT 'Y'`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP COLUMN "deleted_by_id"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD "deleted_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP COLUMN "updated_by_id"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD "updated_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP COLUMN "created_by_id"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD "created_by_id" character varying`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD "requested_organization_id" uuid`);
        await queryRunner.query(`CREATE INDEX "IDX_menu_permission_organization" ON "menu_permission" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_menu_permission_menu" ON "menu_permission" ("menu_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_menu_permission_user" ON "menu_permission" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_menu_to_org_map_menu" ON "menu_to_organization_map" ("menu_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_menu_to_org_map_organization" ON "menu_to_organization_map" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_menu_module_id" ON "menu" ("module_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_module_entry_active" ON "module_entry" ("is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_organization_access_requests_status_created" ON "organization_access_requests" ("created_at", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_organization_access_requests_pending_unique" ON "organization_access_requests" ("requested_by_user_id", "requested_organization_id") WHERE (status = 'pending'::organization_access_requests_status_enum)`);
        await queryRunner.query(`CREATE INDEX "IDX_uom_organization" ON "uom" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_styles_organization" ON "styles" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_size_organization" ON "size" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_color_organization" ON "color" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_embellishment_organization" ON "embellishment" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_buyer_organization" ON "buyer" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_country_organization" ON "country" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_currency_organization" ON "currency" ("organization_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_to_oranization_map_default_per_user" ON "user_to_oranization_map" ("user_id") WHERE (is_default = true)`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_menu_permission_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_menu_permission_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_menu_permission_menu" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_menu_to_org_map_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_menu_to_org_map_menu" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_menu_module" FOREIGN KEY ("module_id") REFERENCES "module_entry"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_organization_access_requests_updated_by_user" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_organization_access_requests_reviewed_by_user" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_organization_access_requests_requested_organization" FOREIGN KEY ("requested_organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_organization_access_requests_requested_by_user" FOREIGN KEY ("requested_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_organization_access_requests_requested_admin_user" FOREIGN KEY ("requested_admin_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_organization_access_requests_deleted_by_user" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_organization_access_requests_created_by_user" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "FK_uom_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "styles" ADD CONSTRAINT "FK_styles_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "size" ADD CONSTRAINT "FK_size_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "color" ADD CONSTRAINT "FK_color_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embellishment" ADD CONSTRAINT "FK_embellishment_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyer" ADD CONSTRAINT "FK_buyer_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country" ADD CONSTRAINT "FK_country_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "FK_currency_organization" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_updated_by_user" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_deleted_by_user" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_notifications_created_by_user" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD CONSTRAINT "FK_user_firebase_tokens_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
