import { MigrationInterface, QueryRunner } from "typeorm";

export class FirstMigration1778091081161 implements MigrationInterface {
    name = 'FirstMigration1778091081161'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."files_file_type_enum" AS ENUM('document', 'receipt', 'photo', 'video', 'audio', 'other', 'image')`);
        await queryRunner.query(`CREATE TYPE "public"."files_file_category_enum" AS ENUM('personal', 'financial', 'medical', 'administrative', 'other')`);
        await queryRunner.query(`CREATE TABLE "files" ("id" SERIAL NOT NULL, "file_name" character varying(255) NOT NULL, "original_name" character varying(255) NOT NULL, "file_path" character varying(500) NOT NULL, "file_size" bigint NOT NULL, "mime_type" character varying(100) NOT NULL, "file_type" "public"."files_file_type_enum" NOT NULL DEFAULT 'other', "file_category" "public"."files_file_category_enum" NOT NULL DEFAULT 'other', "uploaded_by" uuid, "uploaded_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "public_url" character varying, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "address" character varying, "contact" character varying, CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_to_oranization_map_role_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`CREATE TABLE "user_to_oranization_map" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "user_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "role" "public"."user_to_oranization_map_role_enum" NOT NULL DEFAULT 'user', "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_132a609cd36ee3aa205627c7bb6" PRIMARY KEY ("user_id", "organization_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_gender_enum" AS ENUM('male', 'female', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "users" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "recovery_email" character varying, "phone_no" character varying NOT NULL, "date_of_birth" TIMESTAMP NOT NULL, "gender" "public"."users_gender_enum" NOT NULL, "user_name" character varying NOT NULL, "password" character varying NOT NULL, "profile_pic_id" integer, "bio" character varying, "role" "public"."users_role_enum" NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'inactive', "last_seen_at" TIMESTAMP, "is_enable_notifications" boolean NOT NULL DEFAULT true, "is_email_verified" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_074a1f262efaca6aba16f7ed920" UNIQUE ("user_name"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_users_recovery_email_unique" ON "users" ("recovery_email") WHERE "recovery_email" IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "delete_account" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "is_irrelevant_content" boolean NOT NULL DEFAULT false, "is_negative_community" boolean NOT NULL DEFAULT false, "is_no_activity" boolean NOT NULL DEFAULT false, "is_too_time_consuming" boolean NOT NULL DEFAULT false, "is_other" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_ebaea94d4cde435c35ca6eba1be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_firebase_tokens" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" text NOT NULL, "platform" character varying, "user_agent" text, "last_seen_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_69973c7b05e5a9a9fbecb51e8f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_user_firebase_tokens_token" ON "user_firebase_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_firebase_tokens_user" ON "user_firebase_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "users_location" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "location" geography(Point,4326) NOT NULL, "latitude" double precision NOT NULL, "longitude" double precision NOT NULL, "area" character varying, "city" character varying, "state" character varying, "country" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_1523fb2aebce55b9e820122ee0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_userlocation_user_id" ON "users_location" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_userlocation_location" ON "users_location" USING GiST ("location") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('organization_access_request', 'organization_access_request_decision')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL, "body" text NOT NULL, "link" character varying, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'organization_access_request', "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "metadata" jsonb, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_user_read" ON "notifications" ("user_id", "is_read") `);
        await queryRunner.query(`CREATE TABLE "file_references" ("id" SERIAL NOT NULL, "file_id" integer NOT NULL, "resource" character varying(50) NOT NULL, "resource_id" integer NOT NULL, "reference_type" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_29140177cb876eafdee7340dccc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."contact_contact_catagory_enum" AS ENUM('Bug Report', 'Feature Request', 'Account Issues', 'Feedback & Suggesttions', 'Partnership Inquiry', 'Payment & Billing', 'Other')`);
        await queryRunner.query(`CREATE TABLE "contact" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contact_catagory" "public"."contact_contact_catagory_enum" NOT NULL DEFAULT 'Other', "remarks" character varying, CONSTRAINT "PK_2cbbe00f59ab6b3bb5b8d19f989" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "code" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "userId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isUsed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "userId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isRevoked" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "email_verification_tokens" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "code" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "userId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isUsed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_417a095bbed21c2369a6a01ab9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "currency" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" SERIAL NOT NULL, "currencyname" character varying NOT NULL, "currencycode" character varying NOT NULL, "organization_id" uuid, "rate" double precision NOT NULL, "symbol" character varying NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_3cda65c731a6264f0e444cc9b91" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "country" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" SERIAL NOT NULL, "name" character varying NOT NULL, "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_bf6e37c231c4f4ea56dcd887269" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "buyer" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "display_name" character varying NOT NULL, "contact" character varying, "email" character varying, "country_id" integer, "organization_id" uuid, "address" character varying, "remarks" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0480fc3c7289846a31b8e1bc503" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "embellishment" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" SERIAL NOT NULL, "name" character varying NOT NULL, "remarks" text, "organization_id" uuid, "is_active" character varying(10) NOT NULL DEFAULT 'Y', CONSTRAINT "PK_e029c6f80f9b90439306df055b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "style_to_embellishment_map" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" SERIAL NOT NULL, "embellishment_id" integer NOT NULL, "style_id" uuid NOT NULL, CONSTRAINT "PK_56a2828cb7d2c09144df36bc6ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "color" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" SERIAL NOT NULL, "color_name" character varying NOT NULL, "color_display_name" character varying, "organization_id" uuid, "color_description" text, "color_hex_code" character varying, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_d15e531d60a550fbf23e1832343" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "style_to_color_map" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" SERIAL NOT NULL, "color_id" integer NOT NULL, "style_id" uuid NOT NULL, CONSTRAINT "PK_376e0f23923a1046f5dd08b8239" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "size" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" SERIAL NOT NULL, "size_name" character varying NOT NULL, "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_66e3a0111d969aa0e5f73855c7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "style_to_size_map" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" SERIAL NOT NULL, "size_id" integer NOT NULL, "style_id" uuid NOT NULL, CONSTRAINT "PK_bc6df015c0c123b64ab76343b9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "styles" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_type" character varying(255), "buyer_id" uuid NOT NULL, "organization_id" uuid, "style_no" character varying(255) NOT NULL, "style_name" character varying(255), "item_type" character varying(255), "product_department" character varying(255), "cm_sewing" double precision NOT NULL DEFAULT '0', "currency_id" integer NOT NULL, "smv_sewing" double precision NOT NULL DEFAULT '0', "smv_sewing_side_seam" double precision NOT NULL DEFAULT '0', "smv_cutting" double precision NOT NULL DEFAULT '0', "smv_cutting_side_seam" integer NOT NULL DEFAULT '0', "smv_finishing" double precision NOT NULL DEFAULT '0', "image_id" integer, "remarks" text, "is_active" boolean NOT NULL DEFAULT true, "item_uom" character varying(100), "product_family" character varying(255), CONSTRAINT "PK_1f22d2e5045f508c5fce0eb6e86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_order" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "pono" character varying(50) NOT NULL, CONSTRAINT "UQ_492fa29c977d9ba821bb3824b07" UNIQUE ("pono"), CONSTRAINT "PK_ad3e1c7b862f4043b103a6c8c60" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "factory" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "display_name" character varying NOT NULL, "code" character varying, "contact" character varying, "email" character varying, "image_id" integer, "organization_id" uuid, "address" character varying, "remarks" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_1372e5a7d114a3fa80736ba66bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hr-designations" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "designation_name" character varying(255) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_3bba291f76e3886714946b0bcda" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "department_name" character varying(255) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."employees_gender_enum" AS ENUM('Male', 'Female', 'Others')`);
        await queryRunner.query(`CREATE TABLE "employees" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "factory_id" uuid NOT NULL, "organization_id" uuid NOT NULL, "employee_code" character varying(100) NOT NULL, "employee_name" character varying(255) NOT NULL, "designation_id" uuid, "department_id" uuid, "image_id" integer, "phone_no" character varying(50), "email" character varying(255), "gender" "public"."employees_gender_enum", "joining_date" date, "nid_no" character varying(100), "address" text, "remarks" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."job_ordertype_enum" AS ENUM('Retail', 'Promotional')`);
        await queryRunner.query(`CREATE TABLE "job" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "factory_id" uuid NOT NULL, "buyer_id" uuid NOT NULL, "merchandiser_id" uuid, "ordertype" "public"."job_ordertype_enum", "total_po_qty" numeric(18,4) NOT NULL DEFAULT '0', "po_receive_date" date, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_98ab1c14ff8d1cf80d18703b92f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "job_details" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_id" uuid NOT NULL, "po_id" uuid NOT NULL, "style_id" uuid NOT NULL, "size_id" integer NOT NULL, "color_id" integer NOT NULL, "quantity" numeric(18,4) NOT NULL DEFAULT '0', "fob" numeric(18,4) NOT NULL DEFAULT '0', "cm" numeric(18,4) NOT NULL DEFAULT '0', "delivery_date" date, "remarks" text, CONSTRAINT "PK_daf4f98fa9373023a8e6cba51f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."organization_access_requests_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "organization_access_requests" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requested_by_user_id" uuid NOT NULL, "requested_admin_user_id" uuid NOT NULL, "requested_admin_email" character varying NOT NULL, "message" text, "status" "public"."organization_access_requests_status_enum" NOT NULL DEFAULT 'pending', "reviewed_by_user_id" uuid, "reviewed_at" TIMESTAMP, "review_note" text, CONSTRAINT "PK_b5376fb799e3b920db47223d4c6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_organization_access_requests_pending_admin_unique" ON "organization_access_requests" ("requested_by_user_id", "requested_admin_user_id") WHERE "status" = 'pending'`);
        await queryRunner.query(`CREATE TABLE "uom" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" SERIAL NOT NULL, "name" character varying NOT NULL, "short_name" character varying NOT NULL, "organization_id" uuid, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_87729daf4a43ad4efdbdef69ff9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "module_entry" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "module_name" character varying NOT NULL, "module_key" character varying NOT NULL, "description" text, "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_bccdca198540070091b6b487190" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menu" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "menu_name" character varying NOT NULL, "menu_path" character varying, "module_id" uuid NOT NULL, "description" text, "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_35b2a8f47d153ff7a41860cceeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menu_to_organization_map" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "menu_id" uuid NOT NULL, "organization_id" uuid NOT NULL, CONSTRAINT "PK_007b08f00e9141e48f3a83b7439" PRIMARY KEY ("menu_id", "organization_id"))`);
        await queryRunner.query(`CREATE TABLE "menu_permission" ("created_by_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by_id" uuid, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "user_id" uuid NOT NULL, "menu_id" uuid NOT NULL, "can_view" boolean NOT NULL DEFAULT false, "can_create" boolean NOT NULL DEFAULT false, "can_update" boolean NOT NULL DEFAULT false, "can_delete" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_7a69d87de538c0e8ad05c1a1820" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_menu_permission_org_user_menu_active" ON "menu_permission" ("organization_id", "user_id", "menu_id") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_d3c5f450939bf4fd56f844823cf" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_7ef7dd65e5789c70cdd8326a223" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_4b7c0f48c60c0a170061d104adf" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" ADD CONSTRAINT "FK_10e5719a2c91527136f2c8d2499" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" ADD CONSTRAINT "FK_0ed71dd73aaef0f96f791c01ab4" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" ADD CONSTRAINT "FK_7da10ed64bba953c65a08a3f2f4" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" ADD CONSTRAINT "FK_fd390d8b946e5120c94b4676ef3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" ADD CONSTRAINT "FK_681f2029a29e50a8a443eeefaa2" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_1bbd34899b8e74ef2a7f3212806" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_80e310e761f458f272c20ea6add" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4241f21b9bb35e82a6217af1aad" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_68a7fe0ccca390885fe1b4f12b7" FOREIGN KEY ("profile_pic_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delete_account" ADD CONSTRAINT "FK_e8ee26fe21a97257b332737b17a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD CONSTRAINT "FK_459c426aa96644dec9c5f4592f4" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD CONSTRAINT "FK_279b368eefe5181cd0dc3ae77b9" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD CONSTRAINT "FK_3ee453584a07b441959281b3b74" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" ADD CONSTRAINT "FK_2383d7b0b279626153d2f65deb9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_location" ADD CONSTRAINT "FK_16957def0e3220fadbf7eece831" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_8abe9303bccd29799a4d435eb03" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_4b5a99e362f41866311bc381b2d" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_104254bdc074b18a64110127250" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_references" ADD CONSTRAINT "FK_2f65aba597220b9e04ce2dd90f8" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact" ADD CONSTRAINT "FK_316c25cbe80d0fbc05884a9337b" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact" ADD CONSTRAINT "FK_90310dbe361d29035cc6ab8303c" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact" ADD CONSTRAINT "FK_29f54cc620e77004046ca191a51" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "FK_10f285d038feb767bf7c2da14b3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "FK_a42fa83f82790badd0c67f9c0c1" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "FK_8692c2116c73441f68e127732f0" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "FK_07605c662cf60d74c5b7ec3c98c" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currency" ADD CONSTRAINT "FK_bd21ca257afac5b2f44fc951073" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country" ADD CONSTRAINT "FK_d4b6d035a533a65d02ba229d3bf" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country" ADD CONSTRAINT "FK_df18c9b1ef90856f1368d92b420" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country" ADD CONSTRAINT "FK_6ba6c46e5dfce6b33d409187d9e" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "country" ADD CONSTRAINT "FK_e5d33a5b71443865b5c6a1eea22" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyer" ADD CONSTRAINT "FK_5f589b57adee48f2e61742a1fcb" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyer" ADD CONSTRAINT "FK_92641e04ff92b756a23be1ce277" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyer" ADD CONSTRAINT "FK_6a6e4e2e4ae66965c42137dfcd6" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyer" ADD CONSTRAINT "FK_84ca5aa0a0a24dbca0a83648b28" FOREIGN KEY ("country_id") REFERENCES "country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyer" ADD CONSTRAINT "FK_403e838f0f6cf324609bb8575ff" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embellishment" ADD CONSTRAINT "FK_6bb636c06eccb0268cfecfc5c5f" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embellishment" ADD CONSTRAINT "FK_eb86598a56cbaf095c02c6fd1c4" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embellishment" ADD CONSTRAINT "FK_1bf8c4e5050913c2fe8ba3791b6" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "embellishment" ADD CONSTRAINT "FK_dc7b2b6cccbb57a0790619c73bc" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" ADD CONSTRAINT "FK_cd10d81dfd74f6d2c51a4f3c624" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" ADD CONSTRAINT "FK_9e5151a53076d2653d10b388083" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" ADD CONSTRAINT "FK_f4a4fae58dcc1a5d7e8e7927b44" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" ADD CONSTRAINT "FK_749a88d94a54cdb9a5d0564ed2c" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" ADD CONSTRAINT "FK_75b515c3c1cfd003ba8b2228290" FOREIGN KEY ("embellishment_id") REFERENCES "embellishment"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "color" ADD CONSTRAINT "FK_8f937b96ee18c1e12f28b7ce13e" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "color" ADD CONSTRAINT "FK_496b0608b9460f394a16222c99e" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "color" ADD CONSTRAINT "FK_3e6532da4a8dba57d7e92318224" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "color" ADD CONSTRAINT "FK_aac149527499d062a6f1a16224a" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" ADD CONSTRAINT "FK_f66e375124539cd7b372e0bd5aa" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" ADD CONSTRAINT "FK_e63294eddf98c5e1e4a604f90d0" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" ADD CONSTRAINT "FK_98778cbcbc53295c83bbd22e8c5" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" ADD CONSTRAINT "FK_c6b5ada1dc656a91166003e0bd1" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" ADD CONSTRAINT "FK_047187f223e5db4dace2c03a7f3" FOREIGN KEY ("color_id") REFERENCES "color"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "size" ADD CONSTRAINT "FK_b7a59bfbab95adf9d1b9d4e6ebf" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "size" ADD CONSTRAINT "FK_1efd3db06638ac517964f131c34" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "size" ADD CONSTRAINT "FK_48a82f81b8454a2a5cc12830f0a" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "size" ADD CONSTRAINT "FK_e07817a7f74ccc73a911612622d" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" ADD CONSTRAINT "FK_b01077d9346f75dc9c0edfb06b6" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" ADD CONSTRAINT "FK_3b9b1fa449427f1bc24eeb1da39" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" ADD CONSTRAINT "FK_6637a2ae5ff12e0b3c03ef882a0" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" ADD CONSTRAINT "FK_091170c2c26ed3b20cd53570eb1" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" ADD CONSTRAINT "FK_434ee01f36da0608c838d7d0287" FOREIGN KEY ("size_id") REFERENCES "size"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "styles" ADD CONSTRAINT "FK_0ecb7bb07bb56139de4e30e9620" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "styles" ADD CONSTRAINT "FK_0a251f5c0bfeea93239db1079d2" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "styles" ADD CONSTRAINT "FK_a8e0f0d9ab356379d8b6cb1d037" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "styles" ADD CONSTRAINT "FK_490d74bd0622561ab514ef2778e" FOREIGN KEY ("buyer_id") REFERENCES "buyer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "styles" ADD CONSTRAINT "FK_fe3905f0b4179308667f52a46b2" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "styles" ADD CONSTRAINT "FK_a9366e2a4e85d28ccecd6b84e2f" FOREIGN KEY ("currency_id") REFERENCES "currency"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "styles" ADD CONSTRAINT "FK_2df19691f32e1177cd1d0593d83" FOREIGN KEY ("image_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_3be9cd04f1379868b39b574c34c" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_909c4f1cbbaa73a16c61d452479" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order" ADD CONSTRAINT "FK_785ffd8c7f2d02c5abace24697e" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory" ADD CONSTRAINT "FK_c0e54466eb0920eab0a39b833a6" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory" ADD CONSTRAINT "FK_8959582eb1954b388ed6d3ef23a" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory" ADD CONSTRAINT "FK_b63dad5ac4839a7763557779b15" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory" ADD CONSTRAINT "FK_dbec80b255833db6be62d5ec639" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "factory" ADD CONSTRAINT "FK_3accde3cbaa577c6c262a3cea5c" FOREIGN KEY ("image_id") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr-designations" ADD CONSTRAINT "FK_c3162a6c4e096759bc07c5ccf83" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr-designations" ADD CONSTRAINT "FK_dc54e5ed0ab4295f0c7f3a3a1b7" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr-designations" ADD CONSTRAINT "FK_0d49692baefa8b5ce93be6ac150" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr-designations" ADD CONSTRAINT "FK_12ae7790717f5a3deec859d1ebb" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_c92e8cfee06c8e18abd172ea9e1" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_d149ad13b484d568edf6171131f" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_5e5b364bfe4e30683d072b125d3" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_71070628c130f2c9cd3cd5f082f" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_61ba790b66d5671db7d46094c19" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_e539c9aef9fd2bc3199fa0e2ff4" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_4e94e124e8019e83ae6bcfcba22" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_9220e61ca603c8e89599e95d23b" FOREIGN KEY ("factory_id") REFERENCES "factory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_3d3bc4729062b93fb56b084d786" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_2de5d6e4fb3345f18bc467017f0" FOREIGN KEY ("designation_id") REFERENCES "hr-designations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_678a3540f843823784b0fe4a4f2" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_0d1c2a06c90311d8c53bfc653bf" FOREIGN KEY ("image_id") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_70a700fa7e6133a31e1bbaecdb8" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_73a9b4ec175f7f03208c33b511a" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_9dbb73400639b68abd14dda83e4" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_ec6b4751839d214fd3802a2fa9d" FOREIGN KEY ("factory_id") REFERENCES "factory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_2756228a62988ab6c4875a94e84" FOREIGN KEY ("merchandiser_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job" ADD CONSTRAINT "FK_483ddd4b5383c7959978afec1da" FOREIGN KEY ("buyer_id") REFERENCES "buyer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_details" ADD CONSTRAINT "FK_e479c92de22c32729d629740c3e" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_details" ADD CONSTRAINT "FK_1f83d40e93c3c9b89ede3333bc2" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_details" ADD CONSTRAINT "FK_0d7dc5bfa65b346d15c0e587add" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_details" ADD CONSTRAINT "FK_d6dac7e08d2dd14a67e31a489bd" FOREIGN KEY ("job_id") REFERENCES "job"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_details" ADD CONSTRAINT "FK_cd84170eec7fc015f0950f64901" FOREIGN KEY ("po_id") REFERENCES "purchase_order"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_details" ADD CONSTRAINT "FK_5b46a56a5fbb033cd6b7ffc0915" FOREIGN KEY ("style_id") REFERENCES "styles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_details" ADD CONSTRAINT "FK_64824cc29df929ff0bd0628aa21" FOREIGN KEY ("size_id") REFERENCES "size"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_details" ADD CONSTRAINT "FK_27649715e2c8719a280b725977b" FOREIGN KEY ("color_id") REFERENCES "color"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_ff216adf95db9488195158439e3" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_7f679ddf7aba1f4aaa6a1a8ad3f" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_69496f6123908e6fa1402cba94a" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_a1b7a1009abf045715d50f92a4e" FOREIGN KEY ("requested_by_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_82c97ce5284af4ce0b98de79b2a" FOREIGN KEY ("requested_admin_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" ADD CONSTRAINT "FK_b5a849368b063f5738ee5a3c8e0" FOREIGN KEY ("reviewed_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "FK_22a21c0de2f25b46f5ca09cf20f" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "FK_9fde0cb346e4a4725d29cc00648" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "FK_183b4e3a3c1e1c7278d2126809a" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "uom" ADD CONSTRAINT "FK_843aee500ddeae1f82e32290d67" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD CONSTRAINT "FK_d85fae0200638edf5716e924d6d" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD CONSTRAINT "FK_0634d875dd0aef4069eff1d7422" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "module_entry" ADD CONSTRAINT "FK_7eecd8afdf4f706ccc31e5186b9" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_3897d3db594dbeb79b057026bfb" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_7d328b7644258940a6f5190e745" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_a13e8815bbd246baedd2bb13eec" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_d68a151a9ee82114c44aa7dee5f" FOREIGN KEY ("module_id") REFERENCES "module_entry"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_183277307f37ad2d617af8c2ab2" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_52b53b913acc50551f861cc4c13" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_b4177ebd06c162d958074e4a8b9" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_2e5a31dce6a84351342bc318614" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" ADD CONSTRAINT "FK_e1ae7e97a01b0745e200258eff0" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_7801af81a04b6ffeec445f15d27" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_780dd539248c486ef69c48172e5" FOREIGN KEY ("updated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_14fc1f4e99ce05b30fd19c636a1" FOREIGN KEY ("deleted_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_f5041fba59a63e32cbd0bcb900d" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_8ab337e75d1f19a11a6b3dc2de4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_permission" ADD CONSTRAINT "FK_b3c8638bfd2ffedfc593ba3d034" FOREIGN KEY ("menu_id") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_b3c8638bfd2ffedfc593ba3d034"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_8ab337e75d1f19a11a6b3dc2de4"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_f5041fba59a63e32cbd0bcb900d"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_14fc1f4e99ce05b30fd19c636a1"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_780dd539248c486ef69c48172e5"`);
        await queryRunner.query(`ALTER TABLE "menu_permission" DROP CONSTRAINT "FK_7801af81a04b6ffeec445f15d27"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_e1ae7e97a01b0745e200258eff0"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_2e5a31dce6a84351342bc318614"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_b4177ebd06c162d958074e4a8b9"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_52b53b913acc50551f861cc4c13"`);
        await queryRunner.query(`ALTER TABLE "menu_to_organization_map" DROP CONSTRAINT "FK_183277307f37ad2d617af8c2ab2"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_d68a151a9ee82114c44aa7dee5f"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_a13e8815bbd246baedd2bb13eec"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_7d328b7644258940a6f5190e745"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_3897d3db594dbeb79b057026bfb"`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP CONSTRAINT "FK_7eecd8afdf4f706ccc31e5186b9"`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP CONSTRAINT "FK_0634d875dd0aef4069eff1d7422"`);
        await queryRunner.query(`ALTER TABLE "module_entry" DROP CONSTRAINT "FK_d85fae0200638edf5716e924d6d"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "FK_843aee500ddeae1f82e32290d67"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "FK_183b4e3a3c1e1c7278d2126809a"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "FK_9fde0cb346e4a4725d29cc00648"`);
        await queryRunner.query(`ALTER TABLE "uom" DROP CONSTRAINT "FK_22a21c0de2f25b46f5ca09cf20f"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_b5a849368b063f5738ee5a3c8e0"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_82c97ce5284af4ce0b98de79b2a"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_a1b7a1009abf045715d50f92a4e"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_69496f6123908e6fa1402cba94a"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_7f679ddf7aba1f4aaa6a1a8ad3f"`);
        await queryRunner.query(`ALTER TABLE "organization_access_requests" DROP CONSTRAINT "FK_ff216adf95db9488195158439e3"`);
        await queryRunner.query(`ALTER TABLE "job_details" DROP CONSTRAINT "FK_27649715e2c8719a280b725977b"`);
        await queryRunner.query(`ALTER TABLE "job_details" DROP CONSTRAINT "FK_64824cc29df929ff0bd0628aa21"`);
        await queryRunner.query(`ALTER TABLE "job_details" DROP CONSTRAINT "FK_5b46a56a5fbb033cd6b7ffc0915"`);
        await queryRunner.query(`ALTER TABLE "job_details" DROP CONSTRAINT "FK_cd84170eec7fc015f0950f64901"`);
        await queryRunner.query(`ALTER TABLE "job_details" DROP CONSTRAINT "FK_d6dac7e08d2dd14a67e31a489bd"`);
        await queryRunner.query(`ALTER TABLE "job_details" DROP CONSTRAINT "FK_0d7dc5bfa65b346d15c0e587add"`);
        await queryRunner.query(`ALTER TABLE "job_details" DROP CONSTRAINT "FK_1f83d40e93c3c9b89ede3333bc2"`);
        await queryRunner.query(`ALTER TABLE "job_details" DROP CONSTRAINT "FK_e479c92de22c32729d629740c3e"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_483ddd4b5383c7959978afec1da"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_2756228a62988ab6c4875a94e84"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_ec6b4751839d214fd3802a2fa9d"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_9dbb73400639b68abd14dda83e4"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_73a9b4ec175f7f03208c33b511a"`);
        await queryRunner.query(`ALTER TABLE "job" DROP CONSTRAINT "FK_70a700fa7e6133a31e1bbaecdb8"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_0d1c2a06c90311d8c53bfc653bf"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_678a3540f843823784b0fe4a4f2"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_2de5d6e4fb3345f18bc467017f0"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_3d3bc4729062b93fb56b084d786"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_9220e61ca603c8e89599e95d23b"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_4e94e124e8019e83ae6bcfcba22"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_e539c9aef9fd2bc3199fa0e2ff4"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_61ba790b66d5671db7d46094c19"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_71070628c130f2c9cd3cd5f082f"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_5e5b364bfe4e30683d072b125d3"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_d149ad13b484d568edf6171131f"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_c92e8cfee06c8e18abd172ea9e1"`);
        await queryRunner.query(`ALTER TABLE "hr-designations" DROP CONSTRAINT "FK_12ae7790717f5a3deec859d1ebb"`);
        await queryRunner.query(`ALTER TABLE "hr-designations" DROP CONSTRAINT "FK_0d49692baefa8b5ce93be6ac150"`);
        await queryRunner.query(`ALTER TABLE "hr-designations" DROP CONSTRAINT "FK_dc54e5ed0ab4295f0c7f3a3a1b7"`);
        await queryRunner.query(`ALTER TABLE "hr-designations" DROP CONSTRAINT "FK_c3162a6c4e096759bc07c5ccf83"`);
        await queryRunner.query(`ALTER TABLE "factory" DROP CONSTRAINT "FK_3accde3cbaa577c6c262a3cea5c"`);
        await queryRunner.query(`ALTER TABLE "factory" DROP CONSTRAINT "FK_dbec80b255833db6be62d5ec639"`);
        await queryRunner.query(`ALTER TABLE "factory" DROP CONSTRAINT "FK_b63dad5ac4839a7763557779b15"`);
        await queryRunner.query(`ALTER TABLE "factory" DROP CONSTRAINT "FK_8959582eb1954b388ed6d3ef23a"`);
        await queryRunner.query(`ALTER TABLE "factory" DROP CONSTRAINT "FK_c0e54466eb0920eab0a39b833a6"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_785ffd8c7f2d02c5abace24697e"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_909c4f1cbbaa73a16c61d452479"`);
        await queryRunner.query(`ALTER TABLE "purchase_order" DROP CONSTRAINT "FK_3be9cd04f1379868b39b574c34c"`);
        await queryRunner.query(`ALTER TABLE "styles" DROP CONSTRAINT "FK_2df19691f32e1177cd1d0593d83"`);
        await queryRunner.query(`ALTER TABLE "styles" DROP CONSTRAINT "FK_a9366e2a4e85d28ccecd6b84e2f"`);
        await queryRunner.query(`ALTER TABLE "styles" DROP CONSTRAINT "FK_fe3905f0b4179308667f52a46b2"`);
        await queryRunner.query(`ALTER TABLE "styles" DROP CONSTRAINT "FK_490d74bd0622561ab514ef2778e"`);
        await queryRunner.query(`ALTER TABLE "styles" DROP CONSTRAINT "FK_a8e0f0d9ab356379d8b6cb1d037"`);
        await queryRunner.query(`ALTER TABLE "styles" DROP CONSTRAINT "FK_0a251f5c0bfeea93239db1079d2"`);
        await queryRunner.query(`ALTER TABLE "styles" DROP CONSTRAINT "FK_0ecb7bb07bb56139de4e30e9620"`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" DROP CONSTRAINT "FK_434ee01f36da0608c838d7d0287"`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" DROP CONSTRAINT "FK_091170c2c26ed3b20cd53570eb1"`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" DROP CONSTRAINT "FK_6637a2ae5ff12e0b3c03ef882a0"`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" DROP CONSTRAINT "FK_3b9b1fa449427f1bc24eeb1da39"`);
        await queryRunner.query(`ALTER TABLE "style_to_size_map" DROP CONSTRAINT "FK_b01077d9346f75dc9c0edfb06b6"`);
        await queryRunner.query(`ALTER TABLE "size" DROP CONSTRAINT "FK_e07817a7f74ccc73a911612622d"`);
        await queryRunner.query(`ALTER TABLE "size" DROP CONSTRAINT "FK_48a82f81b8454a2a5cc12830f0a"`);
        await queryRunner.query(`ALTER TABLE "size" DROP CONSTRAINT "FK_1efd3db06638ac517964f131c34"`);
        await queryRunner.query(`ALTER TABLE "size" DROP CONSTRAINT "FK_b7a59bfbab95adf9d1b9d4e6ebf"`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" DROP CONSTRAINT "FK_047187f223e5db4dace2c03a7f3"`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" DROP CONSTRAINT "FK_c6b5ada1dc656a91166003e0bd1"`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" DROP CONSTRAINT "FK_98778cbcbc53295c83bbd22e8c5"`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" DROP CONSTRAINT "FK_e63294eddf98c5e1e4a604f90d0"`);
        await queryRunner.query(`ALTER TABLE "style_to_color_map" DROP CONSTRAINT "FK_f66e375124539cd7b372e0bd5aa"`);
        await queryRunner.query(`ALTER TABLE "color" DROP CONSTRAINT "FK_aac149527499d062a6f1a16224a"`);
        await queryRunner.query(`ALTER TABLE "color" DROP CONSTRAINT "FK_3e6532da4a8dba57d7e92318224"`);
        await queryRunner.query(`ALTER TABLE "color" DROP CONSTRAINT "FK_496b0608b9460f394a16222c99e"`);
        await queryRunner.query(`ALTER TABLE "color" DROP CONSTRAINT "FK_8f937b96ee18c1e12f28b7ce13e"`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" DROP CONSTRAINT "FK_75b515c3c1cfd003ba8b2228290"`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" DROP CONSTRAINT "FK_749a88d94a54cdb9a5d0564ed2c"`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" DROP CONSTRAINT "FK_f4a4fae58dcc1a5d7e8e7927b44"`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" DROP CONSTRAINT "FK_9e5151a53076d2653d10b388083"`);
        await queryRunner.query(`ALTER TABLE "style_to_embellishment_map" DROP CONSTRAINT "FK_cd10d81dfd74f6d2c51a4f3c624"`);
        await queryRunner.query(`ALTER TABLE "embellishment" DROP CONSTRAINT "FK_dc7b2b6cccbb57a0790619c73bc"`);
        await queryRunner.query(`ALTER TABLE "embellishment" DROP CONSTRAINT "FK_1bf8c4e5050913c2fe8ba3791b6"`);
        await queryRunner.query(`ALTER TABLE "embellishment" DROP CONSTRAINT "FK_eb86598a56cbaf095c02c6fd1c4"`);
        await queryRunner.query(`ALTER TABLE "embellishment" DROP CONSTRAINT "FK_6bb636c06eccb0268cfecfc5c5f"`);
        await queryRunner.query(`ALTER TABLE "buyer" DROP CONSTRAINT "FK_403e838f0f6cf324609bb8575ff"`);
        await queryRunner.query(`ALTER TABLE "buyer" DROP CONSTRAINT "FK_84ca5aa0a0a24dbca0a83648b28"`);
        await queryRunner.query(`ALTER TABLE "buyer" DROP CONSTRAINT "FK_6a6e4e2e4ae66965c42137dfcd6"`);
        await queryRunner.query(`ALTER TABLE "buyer" DROP CONSTRAINT "FK_92641e04ff92b756a23be1ce277"`);
        await queryRunner.query(`ALTER TABLE "buyer" DROP CONSTRAINT "FK_5f589b57adee48f2e61742a1fcb"`);
        await queryRunner.query(`ALTER TABLE "country" DROP CONSTRAINT "FK_e5d33a5b71443865b5c6a1eea22"`);
        await queryRunner.query(`ALTER TABLE "country" DROP CONSTRAINT "FK_6ba6c46e5dfce6b33d409187d9e"`);
        await queryRunner.query(`ALTER TABLE "country" DROP CONSTRAINT "FK_df18c9b1ef90856f1368d92b420"`);
        await queryRunner.query(`ALTER TABLE "country" DROP CONSTRAINT "FK_d4b6d035a533a65d02ba229d3bf"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "FK_bd21ca257afac5b2f44fc951073"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "FK_07605c662cf60d74c5b7ec3c98c"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "FK_8692c2116c73441f68e127732f0"`);
        await queryRunner.query(`ALTER TABLE "currency" DROP CONSTRAINT "FK_a42fa83f82790badd0c67f9c0c1"`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "FK_10f285d038feb767bf7c2da14b3"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_d6a19d4b4f6c62dcd29daa497e2"`);
        await queryRunner.query(`ALTER TABLE "contact" DROP CONSTRAINT "FK_29f54cc620e77004046ca191a51"`);
        await queryRunner.query(`ALTER TABLE "contact" DROP CONSTRAINT "FK_90310dbe361d29035cc6ab8303c"`);
        await queryRunner.query(`ALTER TABLE "contact" DROP CONSTRAINT "FK_316c25cbe80d0fbc05884a9337b"`);
        await queryRunner.query(`ALTER TABLE "file_references" DROP CONSTRAINT "FK_2f65aba597220b9e04ce2dd90f8"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_104254bdc074b18a64110127250"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_4b5a99e362f41866311bc381b2d"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_8abe9303bccd29799a4d435eb03"`);
        await queryRunner.query(`ALTER TABLE "users_location" DROP CONSTRAINT "FK_16957def0e3220fadbf7eece831"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP CONSTRAINT "FK_2383d7b0b279626153d2f65deb9"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP CONSTRAINT "FK_3ee453584a07b441959281b3b74"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP CONSTRAINT "FK_279b368eefe5181cd0dc3ae77b9"`);
        await queryRunner.query(`ALTER TABLE "user_firebase_tokens" DROP CONSTRAINT "FK_459c426aa96644dec9c5f4592f4"`);
        await queryRunner.query(`ALTER TABLE "delete_account" DROP CONSTRAINT "FK_e8ee26fe21a97257b332737b17a"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_68a7fe0ccca390885fe1b4f12b7"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4241f21b9bb35e82a6217af1aad"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_80e310e761f458f272c20ea6add"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_1bbd34899b8e74ef2a7f3212806"`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" DROP CONSTRAINT "FK_681f2029a29e50a8a443eeefaa2"`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" DROP CONSTRAINT "FK_fd390d8b946e5120c94b4676ef3"`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" DROP CONSTRAINT "FK_7da10ed64bba953c65a08a3f2f4"`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" DROP CONSTRAINT "FK_0ed71dd73aaef0f96f791c01ab4"`);
        await queryRunner.query(`ALTER TABLE "user_to_oranization_map" DROP CONSTRAINT "FK_10e5719a2c91527136f2c8d2499"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_4b7c0f48c60c0a170061d104adf"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_7ef7dd65e5789c70cdd8326a223"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_d3c5f450939bf4fd56f844823cf"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_63c92c51cd7fd95c2d79d709b61"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_menu_permission_org_user_menu_active"`);
        await queryRunner.query(`DROP TABLE "menu_permission"`);
        await queryRunner.query(`DROP TABLE "menu_to_organization_map"`);
        await queryRunner.query(`DROP TABLE "menu"`);
        await queryRunner.query(`DROP TABLE "module_entry"`);
        await queryRunner.query(`DROP TABLE "uom"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_organization_access_requests_pending_admin_unique"`);
        await queryRunner.query(`DROP TABLE "organization_access_requests"`);
        await queryRunner.query(`DROP TYPE "public"."organization_access_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "job_details"`);
        await queryRunner.query(`DROP TABLE "job"`);
        await queryRunner.query(`DROP TYPE "public"."job_ordertype_enum"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TYPE "public"."employees_gender_enum"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "hr-designations"`);
        await queryRunner.query(`DROP TABLE "factory"`);
        await queryRunner.query(`DROP TABLE "purchase_order"`);
        await queryRunner.query(`DROP TABLE "styles"`);
        await queryRunner.query(`DROP TABLE "style_to_size_map"`);
        await queryRunner.query(`DROP TABLE "size"`);
        await queryRunner.query(`DROP TABLE "style_to_color_map"`);
        await queryRunner.query(`DROP TABLE "color"`);
        await queryRunner.query(`DROP TABLE "style_to_embellishment_map"`);
        await queryRunner.query(`DROP TABLE "embellishment"`);
        await queryRunner.query(`DROP TABLE "buyer"`);
        await queryRunner.query(`DROP TABLE "country"`);
        await queryRunner.query(`DROP TABLE "currency"`);
        await queryRunner.query(`DROP TABLE "email_verification_tokens"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "contact"`);
        await queryRunner.query(`DROP TYPE "public"."contact_contact_catagory_enum"`);
        await queryRunner.query(`DROP TABLE "file_references"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_user_read"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_userlocation_location"`);
        await queryRunner.query(`DROP INDEX "public"."idx_userlocation_user_id"`);
        await queryRunner.query(`DROP TABLE "users_location"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_firebase_tokens_user"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_user_firebase_tokens_token"`);
        await queryRunner.query(`DROP TABLE "user_firebase_tokens"`);
        await queryRunner.query(`DROP TABLE "delete_account"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_users_recovery_email_unique"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_gender_enum"`);
        await queryRunner.query(`DROP TABLE "user_to_oranization_map"`);
        await queryRunner.query(`DROP TYPE "public"."user_to_oranization_map_role_enum"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TYPE "public"."files_file_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."files_file_type_enum"`);
    }

}
