import { MigrationInterface, QueryRunner } from "typeorm";

export class FirstMigration1787023623980 implements MigrationInterface {
    name = 'FirstMigration1787023623980'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE OR REPLACE FUNCTION hr_prevent_audit_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'HR audit events are immutable'; END; $$ LANGUAGE plpgsql`);
        await queryRunner.query(`CREATE TABLE "hr_organization_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "timezone" character varying(80) NOT NULL DEFAULT 'Asia/Dhaka', "currency" character varying(3) NOT NULL DEFAULT 'BDT', "leave_approval_levels" smallint NOT NULL DEFAULT '1', "attendance_rounding_minutes" smallint NOT NULL DEFAULT '1', "overtime_cap_minutes" integer, "settings" jsonb NOT NULL DEFAULT '{}'::jsonb, CONSTRAINT "uq_hr_organization_settings" UNIQUE ("organization_id"), CONSTRAINT "PK_hr_organization_settings" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0221d829ff873de389892e87a8" ON "hr_organization_settings" ("organization_id")`);
        await queryRunner.query(`CREATE TYPE "public"."hr_master_data_type_enum" AS ENUM('EMPLOYMENT_TYPE', 'GRADE', 'PAY_GROUP', 'WORK_LOCATION', 'HOLIDAY_CALENDAR', 'LEAVE_TYPE', 'SALARY_COMPONENT', 'SEPARATION_REASON')`);
        await queryRunner.query(`CREATE TABLE "hr_master_data" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "type" "public"."hr_master_data_type_enum" NOT NULL, "code" character varying(80) NOT NULL, "name" character varying(255) NOT NULL, "name_bn" character varying(255), "settings" jsonb NOT NULL DEFAULT '{}'::jsonb, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "uq_hr_master_data_org_type_code" UNIQUE ("organization_id", "type", "code"), CONSTRAINT "PK_110478ec943e14732a3895c4ac0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dca7c335409a1a2165d6f2c4b0" ON "hr_master_data" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc0c27745829dbdfe2a96d5309" ON "hr_master_data" ("type") `);
        await queryRunner.query(`CREATE TABLE "hr_audit_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "actor_id" uuid, "action" character varying(120) NOT NULL, "subject_type" character varying(120) NOT NULL, "subject_id" character varying(120) NOT NULL, "before_state" jsonb, "after_state" jsonb, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0129092cebfb961f8119470774a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TRIGGER trg_hr_audit_immutable BEFORE UPDATE OR DELETE ON "hr_audit_events" FOR EACH ROW EXECUTE FUNCTION hr_prevent_audit_mutation()`);
        await queryRunner.query(`CREATE INDEX "idx_hr_audit_tenant_subject" ON "hr_audit_events" ("organization_id", "subject_type", "subject_id") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_employee_employment_history_action_enum" AS ENUM('ACTIVATE', 'TRANSFER', 'PROMOTE', 'CONFIRM', 'SUSPEND', 'RESIGN', 'TERMINATE', 'RETIRE', 'REHIRE')`);
        await queryRunner.query(`CREATE TABLE "hr_employee_employment_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "employee_id" uuid NOT NULL, "action" "public"."hr_employee_employment_history_action_enum" NOT NULL, "effective_from" date NOT NULL, "effective_to" date, "factory_id" uuid, "department_id" uuid, "designation_id" uuid, "supervisor_id" uuid, "grade_id" uuid, "pay_group_id" uuid, "reason" text, CONSTRAINT "PK_1fa87eed25719e497b4b6058e28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_520607bcb19f3631c099a5d340" ON "hr_employee_employment_history" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_hr_employment_history_effective" ON "hr_employee_employment_history" ("organization_id", "employee_id", "effective_from") `);
        await queryRunner.query(`CREATE TABLE "hr_shifts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "code" character varying(80) NOT NULL, "name" character varying(255) NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "break_minutes" integer NOT NULL DEFAULT '0', "grace_in_minutes" integer NOT NULL DEFAULT '0', "grace_out_minutes" integer NOT NULL DEFAULT '0', "overtime_after_minutes" integer NOT NULL DEFAULT '0', "is_overnight" boolean NOT NULL DEFAULT false, "is_flexible" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "uq_hr_shift_org_code" UNIQUE ("organization_id", "code"), CONSTRAINT "PK_ab17dc646abeecad9f255f573f7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0d7a49fab05c722db4844daad1" ON "hr_shifts" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "hr_roster_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "employee_id" uuid NOT NULL, "shift_id" uuid NOT NULL, "effective_from" date NOT NULL, "effective_to" date, "weekly_off_days" smallint array NOT NULL DEFAULT '{5}', CONSTRAINT "PK_23558b71de90823fdccd60d6839" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1c933ca7960a4a6bb9b810cfb7" ON "hr_roster_assignments" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_hr_roster_employee_dates" ON "hr_roster_assignments" ("organization_id", "employee_id", "effective_from", "effective_to") `);
        await queryRunner.query(`CREATE TABLE "hr_attendance_integration_credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "source" character varying(120) NOT NULL, "key_prefix" character varying(16) NOT NULL, "secret_hash" character varying(255) NOT NULL, "allowed_ips" text array NOT NULL DEFAULT '{}', "revoked_at" TIMESTAMP WITH TIME ZONE, "last_used_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "uq_hr_attendance_credential_source" UNIQUE ("organization_id", "source"), CONSTRAINT "PK_9690dacf83ea81a28c58d3a93f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dfe7242a6218eb755ee6568f3a" ON "hr_attendance_integration_credentials" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_attendance_punches_direction_enum" AS ENUM('IN', 'OUT', 'UNKNOWN')`);
        await queryRunner.query(`CREATE TABLE "hr_attendance_punches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "employee_id" uuid NOT NULL, "source" character varying(120) NOT NULL, "external_event_id" character varying(255) NOT NULL, "punched_at" TIMESTAMP WITH TIME ZONE NOT NULL, "direction" "public"."hr_attendance_punches_direction_enum" NOT NULL DEFAULT 'UNKNOWN', "device_identifier" character varying(255), "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "uq_hr_punch_source_external" UNIQUE ("organization_id", "source", "external_event_id"), CONSTRAINT "PK_f879c90a52cc48c11c650d69939" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_hr_punch_employee_time" ON "hr_attendance_punches" ("organization_id", "employee_id", "punched_at") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_attendance_days_status_enum" AS ENUM('PRESENT', 'ABSENT', 'LEAVE', 'HOLIDAY', 'WEEKLY_OFF', 'MISSING_PUNCH')`);
        await queryRunner.query(`CREATE TABLE "hr_attendance_days" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "employee_id" uuid NOT NULL, "work_date" date NOT NULL, "shift_id" uuid, "status" "public"."hr_attendance_days_status_enum" NOT NULL, "first_in" TIMESTAMP WITH TIME ZONE, "last_out" TIMESTAMP WITH TIME ZONE, "worked_minutes" integer NOT NULL DEFAULT '0', "late_minutes" integer NOT NULL DEFAULT '0', "early_exit_minutes" integer NOT NULL DEFAULT '0', "overtime_minutes" integer NOT NULL DEFAULT '0', "is_finalized" boolean NOT NULL DEFAULT false, "calculation_trace" jsonb NOT NULL DEFAULT '{}'::jsonb, CONSTRAINT "uq_hr_attendance_day" UNIQUE ("organization_id", "employee_id", "work_date"), CONSTRAINT "PK_ea60e8577ab76486029ae949d8d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c74b189b98a43194539a0b04bf" ON "hr_attendance_days" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_attendance_corrections_status_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "hr_attendance_corrections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "attendance_day_id" uuid NOT NULL, "requested_values" jsonb NOT NULL, "reason" text NOT NULL, "status" "public"."hr_attendance_corrections_status_enum" NOT NULL DEFAULT 'PENDING', "decided_by_id" uuid, "decided_at" TIMESTAMP WITH TIME ZONE, "decision_comment" text, CONSTRAINT "PK_hr_attendance_corrections" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_080e8aaef3091db3518bd29ea1" ON "hr_attendance_corrections" ("organization_id")`);
        await queryRunner.query(`CREATE INDEX "idx_hr_attendance_correction_day" ON "hr_attendance_corrections" ("organization_id", "attendance_day_id", "status")`);
        await queryRunner.query(`CREATE TYPE "public"."hr_overtime_requests_status_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "hr_overtime_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "employee_id" uuid NOT NULL, "work_date" date NOT NULL, "requested_minutes" integer NOT NULL, "approved_minutes" integer, "reason" text, "status" "public"."hr_overtime_requests_status_enum" NOT NULL DEFAULT 'PENDING', "decided_by_id" uuid, "decided_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_hr_overtime_requests" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41388e6b398a3834c43601b8c9" ON "hr_overtime_requests" ("organization_id")`);
        await queryRunner.query(`CREATE INDEX "idx_hr_overtime_employee_date" ON "hr_overtime_requests" ("organization_id", "employee_id", "work_date")`);
        await queryRunner.query(`CREATE TABLE "hr_leave_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "employee_id" uuid NOT NULL, "leave_type_id" uuid NOT NULL, "period_year" integer NOT NULL, "opening" numeric(10,2) NOT NULL DEFAULT '0', "accrued" numeric(10,2) NOT NULL DEFAULT '0', "used" numeric(10,2) NOT NULL DEFAULT '0', "adjusted" numeric(10,2) NOT NULL DEFAULT '0', "encashed" numeric(10,2) NOT NULL DEFAULT '0', CONSTRAINT "uq_hr_leave_balance_period" UNIQUE ("organization_id", "employee_id", "leave_type_id", "period_year"), CONSTRAINT "PK_08a1326e0c81a85b59f37e36b10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_28fb2b335311e43eed46698820" ON "hr_leave_balances" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_leave_requests_status_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "hr_leave_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "employee_id" uuid NOT NULL, "leave_type_id" uuid NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "days" numeric(10,2) NOT NULL, "is_half_day" boolean NOT NULL DEFAULT false, "reason" text, "status" "public"."hr_leave_requests_status_enum" NOT NULL DEFAULT 'DRAFT', "approval_level" smallint NOT NULL DEFAULT '0', "required_approval_levels" smallint NOT NULL DEFAULT '1', "approval_history" jsonb NOT NULL DEFAULT '[]'::jsonb, CONSTRAINT "PK_ddbe5e3a2d42d0602d1a1a362db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a53a7e1e176627968fc6fe5b78" ON "hr_leave_requests" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_hr_leave_employee_dates" ON "hr_leave_requests" ("organization_id", "employee_id", "start_date", "end_date") `);
        await queryRunner.query(`CREATE TABLE "hr_salary_structures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "code" character varying(80) NOT NULL, "name" character varying(255) NOT NULL, "version" integer NOT NULL DEFAULT '1', "effective_from" date NOT NULL, "effective_to" date, "is_active" boolean NOT NULL DEFAULT false, "locked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "uq_hr_salary_structure_version" UNIQUE ("organization_id", "code", "version"), CONSTRAINT "PK_4003827850382a145c748accf3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ef569772d983e18c889aabad56" ON "hr_salary_structures" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_salary_structure_components_type_enum" AS ENUM('EARNING', 'DEDUCTION', 'EMPLOYER_CONTRIBUTION', 'INFORMATIONAL')`);
        await queryRunner.query(`CREATE TABLE "hr_salary_structure_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "salary_structure_id" uuid NOT NULL, "code" character varying(80) NOT NULL, "name" character varying(255) NOT NULL, "name_bn" character varying(255), "type" "public"."hr_salary_structure_components_type_enum" NOT NULL, "formula" text NOT NULL, "sort_order" integer NOT NULL DEFAULT '0', "is_taxable" boolean NOT NULL DEFAULT false, CONSTRAINT "uq_hr_structure_component" UNIQUE ("salary_structure_id", "code"), CONSTRAINT "PK_7851a4b0f15f8ea14bf94747542" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hr_employee_salary_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "employee_id" uuid NOT NULL, "salary_structure_id" uuid NOT NULL, "effective_from" date NOT NULL, "effective_to" date, "base_amount" numeric(18,4) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'BDT', "component_overrides" jsonb NOT NULL DEFAULT '{}'::jsonb, CONSTRAINT "PK_24d56699cc45aeca23ede566f1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hr_employee_payroll_opening" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "employee_id" uuid NOT NULL, "tax_year" integer NOT NULL, "taxable_income" numeric(18,4) NOT NULL DEFAULT '0', "tax_withheld" numeric(18,4) NOT NULL DEFAULT '0', "earnings" jsonb NOT NULL DEFAULT '{}'::jsonb, "deductions" jsonb NOT NULL DEFAULT '{}'::jsonb, CONSTRAINT "uq_hr_payroll_opening_year" UNIQUE ("organization_id", "employee_id", "tax_year"), CONSTRAINT "PK_hr_employee_payroll_opening" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_26073041563a36a9ce33a1f44e" ON "hr_employee_payroll_opening" ("organization_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_ad42032fa3342cff23af873832" ON "hr_employee_salary_assignments" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_hr_salary_assignment_effective" ON "hr_employee_salary_assignments" ("organization_id", "employee_id", "effective_from") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_loans_status_enum" AS ENUM('DRAFT', 'APPROVED', 'ACTIVE', 'PAUSED', 'SETTLED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "hr_loans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "employee_id" uuid NOT NULL, "loan_number" character varying(80) NOT NULL, "principal" numeric(18,4) NOT NULL, "installment_amount" numeric(18,4) NOT NULL, "outstanding_amount" numeric(18,4) NOT NULL, "status" "public"."hr_loans_status_enum" NOT NULL DEFAULT 'DRAFT', "start_date" date NOT NULL, "remarks" text, CONSTRAINT "PK_234d052ec18318f945e40760ef3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5e93ecfe455db346689545b811" ON "hr_loans" ("organization_id") `);
        await queryRunner.query(`CREATE INDEX "idx_hr_loan_employee" ON "hr_loans" ("organization_id", "employee_id", "status") `);
        await queryRunner.query(`CREATE TABLE "hr_loan_installments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "loan_id" uuid NOT NULL, "due_date" date NOT NULL, "amount" numeric(18,4) NOT NULL, "paid_amount" numeric(18,4) NOT NULL DEFAULT '0', "payroll_employee_id" uuid, "paid_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "uq_hr_loan_installment_period" UNIQUE ("loan_id", "due_date"), CONSTRAINT "PK_93ee0970276bac780ec2a16edeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."hr_statutory_rule_packs_review_status_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "hr_statutory_rule_packs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "code" character varying(80) NOT NULL, "name" character varying(255) NOT NULL, "jurisdiction" character varying(80) NOT NULL DEFAULT 'BD', "version" integer NOT NULL, "effective_from" date NOT NULL, "effective_to" date, "rules" jsonb NOT NULL, "source_url" text NOT NULL, "source_published_at" date, "review_status" "public"."hr_statutory_rule_packs_review_status_enum" NOT NULL DEFAULT 'DRAFT', "approved_by_id" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "locked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "uq_hr_rule_pack_version" UNIQUE ("organization_id", "code", "version"), CONSTRAINT "PK_608cba74ebf28c60ee4b51d7b26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ddf6fdbd67f27f0d0a80d91a86" ON "hr_statutory_rule_packs" ("organization_id") `);
        await queryRunner.query(`CREATE TYPE "public"."hr_payroll_runs_frequency_enum" AS ENUM('WEEKLY', 'BIWEEKLY', 'SEMIMONTHLY', 'MONTHLY')`);
        await queryRunner.query(`CREATE TYPE "public"."hr_payroll_runs_run_type_enum" AS ENUM('REGULAR', 'BONUS', 'ARREARS', 'ADJUSTMENT', 'FINAL_SETTLEMENT', 'REVERSAL')`);
        await queryRunner.query(`CREATE TYPE "public"."hr_payroll_runs_status_enum" AS ENUM('DRAFT', 'CALCULATING', 'PREPARED', 'UNDER_REVIEW', 'APPROVED', 'LOCKED', 'FAILED', 'REVERSED')`);
        await queryRunner.query(`CREATE TABLE "hr_payroll_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "created_by_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by_id" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "row_version" integer NOT NULL, "idempotency_key" character varying(120) NOT NULL, "factory_id" uuid NOT NULL, "pay_group_id" uuid NOT NULL, "frequency" "public"."hr_payroll_runs_frequency_enum" NOT NULL, "run_type" "public"."hr_payroll_runs_run_type_enum" NOT NULL, "sequence" smallint NOT NULL DEFAULT '1', "period_start" date NOT NULL, "period_end" date NOT NULL, "payment_date" date NOT NULL, "status" "public"."hr_payroll_runs_status_enum" NOT NULL DEFAULT 'DRAFT', "currency" character varying(3) NOT NULL DEFAULT 'BDT', "rule_pack_id" uuid, "snapshot_metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "prepared_by_id" uuid, "reviewed_by_id" uuid, "approved_by_id" uuid, "locked_by_id" uuid, "locked_at" TIMESTAMP WITH TIME ZONE, "paid_status" character varying(30) NOT NULL DEFAULT 'UNPAID', "reversal_of_run_id" uuid, CONSTRAINT "uq_hr_payroll_run_scope" UNIQUE ("organization_id", "factory_id", "pay_group_id", "period_start", "period_end", "run_type", "sequence"), CONSTRAINT "PK_8c02c0017885d19031d251016b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d24fc4def1802c2f4fedabaf73" ON "hr_payroll_runs" ("organization_id") `);
        await queryRunner.query(`ALTER TABLE "hr_payroll_runs" ADD CONSTRAINT "uq_hr_payroll_idempotency" UNIQUE ("organization_id", "idempotency_key")`);
        await queryRunner.query(`CREATE INDEX "IDX_cd7e7470b9ab8cf50273ffb900" ON "hr_payroll_runs" ("status") `);
        await queryRunner.query(`CREATE TABLE "hr_payroll_employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payroll_run_id" uuid NOT NULL, "employee_id" uuid NOT NULL, "employee_snapshot" jsonb NOT NULL, "input_snapshot" jsonb NOT NULL, "gross_amount" numeric(18,4) NOT NULL DEFAULT '0', "deduction_amount" numeric(18,4) NOT NULL DEFAULT '0', "employer_contribution_amount" numeric(18,4) NOT NULL DEFAULT '0', "net_amount" numeric(18,4) NOT NULL DEFAULT '0', "warnings" jsonb NOT NULL DEFAULT '[]'::jsonb, "error" text, CONSTRAINT "uq_hr_payroll_employee" UNIQUE ("payroll_run_id", "employee_id"), CONSTRAINT "PK_4695c5669ae79716669dc5a44d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."hr_payroll_lines_type_enum" AS ENUM('EARNING', 'DEDUCTION', 'EMPLOYER_CONTRIBUTION', 'INFORMATIONAL')`);
        await queryRunner.query(`CREATE TABLE "hr_payroll_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payroll_employee_id" uuid NOT NULL, "component_code" character varying(80) NOT NULL, "component_name" character varying(255) NOT NULL, "component_name_bn" character varying(255), "type" "public"."hr_payroll_lines_type_enum" NOT NULL, "amount" numeric(18,4) NOT NULL, "formula" text NOT NULL, "formula_version" integer NOT NULL, "calculation_trace" jsonb NOT NULL, CONSTRAINT "uq_hr_payroll_line_component" UNIQUE ("payroll_employee_id", "component_code"), CONSTRAINT "PK_f93b5ad269879d9b93171c4496f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."hr_jobs_status_enum" AS ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "hr_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "organization_id" uuid NOT NULL, "type" character varying(80) NOT NULL, "status" "public"."hr_jobs_status_enum" NOT NULL DEFAULT 'QUEUED', "payload" jsonb NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "max_attempts" integer NOT NULL DEFAULT '3', "progress" integer NOT NULL DEFAULT '0', "available_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lease_owner" character varying(120), "lease_expires_at" TIMESTAMP WITH TIME ZONE, "result" jsonb, "error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_282b1c0d3a14e15985fcf2b988d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_hr_job_claim" ON "hr_jobs" ("status", "available_at", "lease_expires_at") `);
        await queryRunner.query(`ALTER TABLE "employees" ADD "employment_type_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "grade_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "pay_group_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "work_location_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "supervisor_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "date_of_birth" date`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "marital_status" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "employment_status" character varying(30) NOT NULL DEFAULT 'ACTIVE'`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "tax_status" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "tax_identifier" text`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "bank_details" text`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "emergency_contact" text`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "dependents" jsonb NOT NULL DEFAULT '[]'::jsonb`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "probation_end_date" date`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "confirmation_date" date`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "contract_end_date" date`);
        await queryRunner.query(`ALTER TABLE "employees" ADD "separation_date" date`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_employee_org_factory_code_active" ON "employees" ("organization_id", "factory_id", "employee_code") WHERE deleted_at IS NULL`);
        await queryRunner.query(`CREATE INDEX "idx_employee_payroll_scope" ON "employees" ("organization_id", "factory_id", "pay_group_id", "is_active")`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "nid_no" TYPE text USING "nid_no"::text`);
        await queryRunner.query(`ALTER TABLE "hr_master_data" ADD CONSTRAINT "FK_dca7c335409a1a2165d6f2c4b03" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_organization_settings" ADD CONSTRAINT "FK_0221d829ff873de389892e87a8a" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_employee_employment_history" ADD CONSTRAINT "FK_520607bcb19f3631c099a5d3401" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_employee_employment_history" ADD CONSTRAINT "FK_7d557acc88d6a2daa2bfd459427" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_shifts" ADD CONSTRAINT "FK_0d7a49fab05c722db4844daad10" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_roster_assignments" ADD CONSTRAINT "FK_1c933ca7960a4a6bb9b810cfb73" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_roster_assignments" ADD CONSTRAINT "FK_c5997146f7cd1582f953acb0453" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_roster_assignments" ADD CONSTRAINT "FK_5acf458e8a7a077768ab5d66a93" FOREIGN KEY ("shift_id") REFERENCES "hr_shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_integration_credentials" ADD CONSTRAINT "FK_dfe7242a6218eb755ee6568f3a2" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_punches" ADD CONSTRAINT "FK_02616a89f6622bdd73c1be43ed6" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_days" ADD CONSTRAINT "FK_c74b189b98a43194539a0b04bff" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_corrections" ADD CONSTRAINT "FK_080e8aaef3091db3518bd29ea16" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_corrections" ADD CONSTRAINT "FK_f70abb0dc4b60c9bfb790e2fdbe" FOREIGN KEY ("attendance_day_id") REFERENCES "hr_attendance_days"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_overtime_requests" ADD CONSTRAINT "FK_41388e6b398a3834c43601b8c96" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_overtime_requests" ADD CONSTRAINT "FK_hr_overtime_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_leave_balances" ADD CONSTRAINT "FK_28fb2b335311e43eed466988202" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_leave_requests" ADD CONSTRAINT "FK_a53a7e1e176627968fc6fe5b78d" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_salary_structures" ADD CONSTRAINT "FK_ef569772d983e18c889aabad561" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_salary_structure_components" ADD CONSTRAINT "FK_66e84234b0d98e69c4ca4d1a848" FOREIGN KEY ("salary_structure_id") REFERENCES "hr_salary_structures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_employee_salary_assignments" ADD CONSTRAINT "FK_ad42032fa3342cff23af8738329" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_employee_payroll_opening" ADD CONSTRAINT "FK_26073041563a36a9ce33a1f44ef" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_employee_payroll_opening" ADD CONSTRAINT "FK_hr_opening_employee" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_employee_salary_assignments" ADD CONSTRAINT "FK_4639d770177e2277899b8ce6bdb" FOREIGN KEY ("salary_structure_id") REFERENCES "hr_salary_structures"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_loans" ADD CONSTRAINT "FK_5e93ecfe455db346689545b8114" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_loan_installments" ADD CONSTRAINT "FK_ebdc6347338856564e08bdfd37f" FOREIGN KEY ("loan_id") REFERENCES "hr_loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_statutory_rule_packs" ADD CONSTRAINT "FK_ddf6fdbd67f27f0d0a80d91a864" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_payroll_runs" ADD CONSTRAINT "FK_d24fc4def1802c2f4fedabaf733" FOREIGN KEY ("organization_id") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_payroll_runs" ADD CONSTRAINT "FK_8eed5607d5b42194062c25f993b" FOREIGN KEY ("factory_id") REFERENCES "factory"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_payroll_employees" ADD CONSTRAINT "FK_022a74e61a04e81b5b053271c0d" FOREIGN KEY ("payroll_run_id") REFERENCES "hr_payroll_runs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hr_payroll_lines" ADD CONSTRAINT "FK_647fa38c2ea5c4fa54a9ca1683b" FOREIGN KEY ("payroll_employee_id") REFERENCES "hr_payroll_employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`INSERT INTO "module_entry" ("module_name", "module_key", "description", "display_order", "is_active") SELECT 'HR & Payroll', 'hr-payroll', 'Core human resources and payroll operations', 20, true WHERE NOT EXISTS (SELECT 1 FROM "module_entry" WHERE "module_key" = 'hr-payroll' AND "deleted_at" IS NULL)`);
        await queryRunner.query(`INSERT INTO "menu" ("menu_name", "menu_path", "module_id", "description", "display_order", "is_active") SELECT entries.name, entries.path, module.id, entries.description, entries.display_order, true FROM (VALUES ('Designation Setup', '/hr-payroll/core/designation', 'Designation master data', 1), ('Department Setup', '/hr-payroll/core/department', 'Department master data', 2), ('Employee Setup', '/hr-payroll/employee', 'Employee lifecycle records', 3), ('HR Master Data', '/hr-payroll/core', 'HR configuration', 4), ('Shift Setup', '/hr-payroll/shifts', 'Shift definitions', 5), ('Roster Management', '/hr-payroll/rosters', 'Employee rosters', 6), ('Attendance Management', '/hr-payroll/attendance', 'Attendance and overtime', 7), ('Leave Management', '/hr-payroll/leave', 'Leave balances and approvals', 8), ('Compensation Setup', '/hr-payroll/compensation', 'Salary structures and assignments', 9), ('Loan Management', '/hr-payroll/loans', 'Employee loans', 10), ('Statutory Rules', '/hr-payroll/statutory-rules', 'Effective-dated statutory policies', 11), ('Payroll Processing', '/hr-payroll/payroll-runs', 'Payroll calculation and approvals', 12), ('HR Reports', '/hr-payroll/reports', 'HR and payroll reporting', 13), ('HR Imports', '/hr-payroll/imports', 'Opening and bulk imports', 14)) AS entries(name, path, description, display_order) CROSS JOIN LATERAL (SELECT id FROM "module_entry" WHERE "module_key" = 'hr-payroll' AND "deleted_at" IS NULL ORDER BY "created_at" LIMIT 1) module WHERE NOT EXISTS (SELECT 1 FROM "menu" existing WHERE existing."menu_name" = entries.name AND existing."module_id" = module.id AND existing."deleted_at" IS NULL)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DELETE FROM "menu" WHERE "module_id" IN (SELECT "id" FROM "module_entry" WHERE "module_key" = 'hr-payroll') AND "menu_name" IN ('Designation Setup','Department Setup','Employee Setup','HR Master Data','Shift Setup','Roster Management','Attendance Management','Leave Management','Compensation Setup','Loan Management','Statutory Rules','Payroll Processing','HR Reports','HR Imports')`);
        await queryRunner.query(`DELETE FROM "module_entry" WHERE "module_key" = 'hr-payroll' AND NOT EXISTS (SELECT 1 FROM "menu" WHERE "menu"."module_id" = "module_entry"."id")`);
        await queryRunner.query(`ALTER TABLE "hr_employee_payroll_opening" DROP CONSTRAINT "FK_hr_opening_employee"`);
        await queryRunner.query(`ALTER TABLE "hr_employee_payroll_opening" DROP CONSTRAINT "FK_26073041563a36a9ce33a1f44ef"`);
        await queryRunner.query(`ALTER TABLE "hr_overtime_requests" DROP CONSTRAINT "FK_hr_overtime_employee"`);
        await queryRunner.query(`ALTER TABLE "hr_overtime_requests" DROP CONSTRAINT "FK_41388e6b398a3834c43601b8c96"`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_corrections" DROP CONSTRAINT "FK_f70abb0dc4b60c9bfb790e2fdbe"`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_corrections" DROP CONSTRAINT "FK_080e8aaef3091db3518bd29ea16"`);
        await queryRunner.query(`ALTER TABLE "hr_organization_settings" DROP CONSTRAINT "FK_0221d829ff873de389892e87a8a"`);
        await queryRunner.query(`ALTER TABLE "hr_payroll_lines" DROP CONSTRAINT "FK_647fa38c2ea5c4fa54a9ca1683b"`);
        await queryRunner.query(`ALTER TABLE "hr_payroll_employees" DROP CONSTRAINT "FK_022a74e61a04e81b5b053271c0d"`);
        await queryRunner.query(`ALTER TABLE "hr_payroll_runs" DROP CONSTRAINT "FK_8eed5607d5b42194062c25f993b"`);
        await queryRunner.query(`ALTER TABLE "hr_payroll_runs" DROP CONSTRAINT "FK_d24fc4def1802c2f4fedabaf733"`);
        await queryRunner.query(`ALTER TABLE "hr_statutory_rule_packs" DROP CONSTRAINT "FK_ddf6fdbd67f27f0d0a80d91a864"`);
        await queryRunner.query(`ALTER TABLE "hr_loan_installments" DROP CONSTRAINT "FK_ebdc6347338856564e08bdfd37f"`);
        await queryRunner.query(`ALTER TABLE "hr_loans" DROP CONSTRAINT "FK_5e93ecfe455db346689545b8114"`);
        await queryRunner.query(`ALTER TABLE "hr_employee_salary_assignments" DROP CONSTRAINT "FK_4639d770177e2277899b8ce6bdb"`);
        await queryRunner.query(`ALTER TABLE "hr_employee_salary_assignments" DROP CONSTRAINT "FK_ad42032fa3342cff23af8738329"`);
        await queryRunner.query(`ALTER TABLE "hr_salary_structure_components" DROP CONSTRAINT "FK_66e84234b0d98e69c4ca4d1a848"`);
        await queryRunner.query(`ALTER TABLE "hr_salary_structures" DROP CONSTRAINT "FK_ef569772d983e18c889aabad561"`);
        await queryRunner.query(`ALTER TABLE "hr_leave_requests" DROP CONSTRAINT "FK_a53a7e1e176627968fc6fe5b78d"`);
        await queryRunner.query(`ALTER TABLE "hr_leave_balances" DROP CONSTRAINT "FK_28fb2b335311e43eed466988202"`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_days" DROP CONSTRAINT "FK_c74b189b98a43194539a0b04bff"`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_punches" DROP CONSTRAINT "FK_02616a89f6622bdd73c1be43ed6"`);
        await queryRunner.query(`ALTER TABLE "hr_attendance_integration_credentials" DROP CONSTRAINT "FK_dfe7242a6218eb755ee6568f3a2"`);
        await queryRunner.query(`ALTER TABLE "hr_roster_assignments" DROP CONSTRAINT "FK_5acf458e8a7a077768ab5d66a93"`);
        await queryRunner.query(`ALTER TABLE "hr_roster_assignments" DROP CONSTRAINT "FK_c5997146f7cd1582f953acb0453"`);
        await queryRunner.query(`ALTER TABLE "hr_roster_assignments" DROP CONSTRAINT "FK_1c933ca7960a4a6bb9b810cfb73"`);
        await queryRunner.query(`ALTER TABLE "hr_shifts" DROP CONSTRAINT "FK_0d7a49fab05c722db4844daad10"`);
        await queryRunner.query(`ALTER TABLE "hr_employee_employment_history" DROP CONSTRAINT "FK_7d557acc88d6a2daa2bfd459427"`);
        await queryRunner.query(`ALTER TABLE "hr_employee_employment_history" DROP CONSTRAINT "FK_520607bcb19f3631c099a5d3401"`);
        await queryRunner.query(`ALTER TABLE "hr_master_data" DROP CONSTRAINT "FK_dca7c335409a1a2165d6f2c4b03"`);
        await queryRunner.query(`ALTER TABLE "employees" ALTER COLUMN "nid_no" TYPE character varying(100) USING LEFT("nid_no", 100)`);
        await queryRunner.query(`DROP INDEX "public"."idx_employee_payroll_scope"`);
        await queryRunner.query(`DROP INDEX "public"."uq_employee_org_factory_code_active"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "separation_date"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "contract_end_date"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "confirmation_date"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "probation_end_date"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "dependents"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "emergency_contact"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "bank_details"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "tax_identifier"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "tax_status"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "employment_status"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "marital_status"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "date_of_birth"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "supervisor_id"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "work_location_id"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "pay_group_id"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "grade_id"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP COLUMN "employment_type_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_job_claim"`);
        await queryRunner.query(`DROP TABLE "hr_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."hr_jobs_status_enum"`);
        await queryRunner.query(`DROP TABLE "hr_payroll_lines"`);
        await queryRunner.query(`DROP TYPE "public"."hr_payroll_lines_type_enum"`);
        await queryRunner.query(`DROP TABLE "hr_payroll_employees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd7e7470b9ab8cf50273ffb900"`);
        await queryRunner.query(`ALTER TABLE "hr_payroll_runs" DROP CONSTRAINT "uq_hr_payroll_idempotency"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d24fc4def1802c2f4fedabaf73"`);
        await queryRunner.query(`DROP TABLE "hr_payroll_runs"`);
        await queryRunner.query(`DROP TYPE "public"."hr_payroll_runs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."hr_payroll_runs_run_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."hr_payroll_runs_frequency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ddf6fdbd67f27f0d0a80d91a86"`);
        await queryRunner.query(`DROP TABLE "hr_statutory_rule_packs"`);
        await queryRunner.query(`DROP TYPE "public"."hr_statutory_rule_packs_review_status_enum"`);
        await queryRunner.query(`DROP TABLE "hr_loan_installments"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_loan_employee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e93ecfe455db346689545b811"`);
        await queryRunner.query(`DROP TABLE "hr_loans"`);
        await queryRunner.query(`DROP TYPE "public"."hr_loans_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_salary_assignment_effective"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ad42032fa3342cff23af873832"`);
        await queryRunner.query(`DROP TABLE "hr_employee_payroll_opening"`);
        await queryRunner.query(`DROP TABLE "hr_employee_salary_assignments"`);
        await queryRunner.query(`DROP TABLE "hr_salary_structure_components"`);
        await queryRunner.query(`DROP TYPE "public"."hr_salary_structure_components_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef569772d983e18c889aabad56"`);
        await queryRunner.query(`DROP TABLE "hr_salary_structures"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_leave_employee_dates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a53a7e1e176627968fc6fe5b78"`);
        await queryRunner.query(`DROP TABLE "hr_leave_requests"`);
        await queryRunner.query(`DROP TYPE "public"."hr_leave_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28fb2b335311e43eed46698820"`);
        await queryRunner.query(`DROP TABLE "hr_leave_balances"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c74b189b98a43194539a0b04bf"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_overtime_employee_date"`);
        await queryRunner.query(`DROP TABLE "hr_overtime_requests"`);
        await queryRunner.query(`DROP TYPE "public"."hr_overtime_requests_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_attendance_correction_day"`);
        await queryRunner.query(`DROP TABLE "hr_attendance_corrections"`);
        await queryRunner.query(`DROP TYPE "public"."hr_attendance_corrections_status_enum"`);
        await queryRunner.query(`DROP TABLE "hr_attendance_days"`);
        await queryRunner.query(`DROP TYPE "public"."hr_attendance_days_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_punch_employee_time"`);
        await queryRunner.query(`DROP TABLE "hr_attendance_punches"`);
        await queryRunner.query(`DROP TYPE "public"."hr_attendance_punches_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dfe7242a6218eb755ee6568f3a"`);
        await queryRunner.query(`DROP TABLE "hr_attendance_integration_credentials"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_roster_employee_dates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c933ca7960a4a6bb9b810cfb7"`);
        await queryRunner.query(`DROP TABLE "hr_roster_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d7a49fab05c722db4844daad1"`);
        await queryRunner.query(`DROP TABLE "hr_shifts"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_employment_history_effective"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_520607bcb19f3631c099a5d340"`);
        await queryRunner.query(`DROP TABLE "hr_employee_employment_history"`);
        await queryRunner.query(`DROP TYPE "public"."hr_employee_employment_history_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_hr_audit_tenant_subject"`);
        await queryRunner.query(`DROP TABLE "hr_audit_events"`);
        await queryRunner.query(`DROP FUNCTION hr_prevent_audit_mutation()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc0c27745829dbdfe2a96d5309"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dca7c335409a1a2165d6f2c4b0"`);
        await queryRunner.query(`DROP TABLE "hr_master_data"`);
        await queryRunner.query(`DROP TABLE "hr_organization_settings"`);
        await queryRunner.query(`DROP TYPE "public"."hr_master_data_type_enum"`);
    }

}
